base:
  seed: 42

data_load:
  dataset_csv: 'data/raw/parkinsons_updrs.data'

data_split:
  test_size: 0.2
  trainset_path: 'data/processed/train_parkinson.csv'
  testset_path: 'data/processed/train_parkinson.csv'

train:
  n_estimators: 100 
  learning_rate: 0.1
  max_depth: 3

data:
  filepath: './data/raw/parkinsons_updrs.data'
  processed: './data/processed/'
  models: './models/'
